2024-01-16 15:41:41,401 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:48]
2024-01-16 15:41:51,437 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:48]
2024-01-16 15:46:23,767 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:48]
2024-01-16 15:46:27,514 ERROR: Exception on /user/oly [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\routes.py", line 107, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\base.html", line 57, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\user.html", line 11, in block 'content'
    <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\models.py", line 67, in followers_count
    self.followers.select().subquery())
AttributeError: 'AppenderQuery' object has no attribute 'select'
2024-01-16 15:48:14,483 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:48]
2024-01-16 16:04:17,991 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:50]
2024-01-16 16:04:21,734 ERROR: Exception on /user/oly [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\routes.py", line 107, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\base.html", line 64, in top-level template code
    {% block scripts %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\app\templates\base.html", line 65, in block 'scripts'
    {{ super() }}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
2024-01-16 16:05:47,165 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:50]
2024-01-16 16:08:22,716 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\app\__init__.py:50]
2024-01-18 13:54:30,086 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\app\__init__.py:50]
2024-01-18 17:50:04,233 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:68]
2024-01-18 17:50:10,998 ERROR: Exception on /user/oly [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\main\routes.py", line 67, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: user.html
2024-01-18 17:52:23,368 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:68]
2024-01-19 15:11:39,075 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-19 16:52:49,569 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-19 17:00:11,362 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-19 17:35:21,745 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-19 17:36:28,434 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-19 17:38:33,361 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:01:54,249 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:02:09,350 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
