2024-01-25 14:30:19,393 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:30:32,430 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:44:47,142 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:45:09,686 ERROR: Exception on /messages [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\main\routes.py", line 196, in messages
    Message.timestamp.desc()).paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-01-25 14:49:47,317 ERROR: Exception on /messages [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\main\routes.py", line 196, in messages
    Message.timestamp.desc()).paginate(
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2024-01-25 14:50:02,800 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 14:51:14,068 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 17:16:39,672 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 17:16:54,033 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:72]
2024-01-25 18:28:16,059 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:77]
2024-01-25 18:28:34,050 ERROR: Exception on /user/oly [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\main\routes.py", line 67, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\templates\base.html", line 94, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\templates\user.html", line 28, in block 'content'
    {{ _('Export your posts') }}
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2024-01-25 18:31:17,668 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:77]
2024-02-01 12:00:03,842 INFO: Microblog startup [in C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\__init__.py:80]
2024-02-01 12:00:30,050 ERROR: Exception on /api/users/1 [GET] [in C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\api\users.py", line 8, in get_user
    return db.get_or_404(User, id).to_dict()
  File "C:\Users\user\PycharmProjects\MyFlaskProject\FlaskBlog\ChangeProject\app\models.py", line 204, in to_dict
    'last_seen': self.last_seen.replace(
AttributeError: 'NoneType' object has no attribute 'replace'
